language: node_js
node_js:
  - "9"
env:
  - SCRIPT=lint
  - SCRIPT=build
script:
  - yarn run $SCRIPT
jobs:
  include:
    - stage: deploy
      node_js: "9"
      install:
        - npm install -g yarn
        - yarn --pure-lockfile
        - pip install --user awscli
      script:
        - yarn run build
        - aws s3 cp dist/main.js $S3_URL
      env: ""
cache:
  yarn: true
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
